services:
  pgvector:
    image: pgvector/pgvector:pg18-trixie
    container_name: pg-vector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-vector:/var/lib/postgresql/data

volumes:
  pg-vector:
